In [13]:
# PCA
# 스케일 차이 큼 -> 상관계수 행렬/ 스케일 유사 -> 공분산 행렬
# 개수 결정/ 상관계수 행렬 사용시 고유값 > 1인 값/ 공분산 행렬시 고유값 누적비율 > 80%
from sklearn.decomposition import PCA
import statsmodels.api as sm
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [9]:
path = 'C:\\Users\\moon\\Documents\\posco_academy\\practice_data\\3_bigdata\\'

df_raw = pd.read_csv(path+'체질검사.csv', encoding = 'CP949')

In [10]:
df_raw_x = df_raw.drop('FAT',axis=1)
df_raw_y = df_raw['FAT']
df_raw_y.head()

0    35.2
1    11.8
2    22.2
3    10.6
4    47.5
Name: FAT, dtype: float64

In [11]:
x_cols = df_raw_x.columns

In [14]:
scaler = StandardScaler()
nd_scaled = scaler.fit_transform(df_raw_x)

In [15]:
df_scaled = pd.DataFrame(nd_scaled, columns = x_cols)
df_scaled.head().round(3)

AGE  WEIGHT  HEIGHT   NECK  CHEST  ABDOMEN    HIP  THIGH   KNEE  ANKLE  \
0  0.089   6.281   0.575  5.444  4.205    5.161  6.685  5.324  4.366  3.841   
1 -1.422  -0.372   0.301  0.044 -0.930   -1.250 -0.756 -0.402 -0.993  0.826   
2  1.917  -0.040  -0.451  0.292  0.140    0.227 -0.224 -0.841 -0.121 -0.770   
3  0.963  -1.063  -1.203 -1.151 -0.146   -0.572 -1.371 -1.223 -1.492 -1.066   
4  0.486   1.366  -1.682  1.322  2.255    2.745  1.804  0.591 -0.702  0.294   

   BICEPS  FOREARM  WRIST  
0   4.221    0.167  3.403  
1  -1.086    0.663  0.612  
2  -0.489   -1.470  0.612  
3  -0.190   -0.676 -1.427  
4   0.805    0.216  0.183

In [16]:
pca = PCA(n_components=6)
nd_pca = pca.fit_transform(df_scaled)
print(nd_pca[:5])

[[15.14078652  0.74918006  1.73038829  2.97562799 -1.20140416  1.91649244]
 [-1.25745311 -1.79805793 -0.60359147 -0.4059414   1.33324667  0.82223682]
 [-0.72744205  2.31886158 -0.89209681  0.68258035 -0.50328047  0.60020938]
 [-3.21015592  1.46511228  0.45790754 -0.57563715  0.01977212 -0.17880332]
 [ 3.24650172  2.29304235  1.82833929 -0.02336594 -0.40697879  1.14656798]]


In [17]:
df_pca = pd.DataFrame(nd_pca, columns = ['Prin1','Prin2','Prin3','Prin4','Prin5','Print6'])
df_scaled_pca = df_scaled.join(df_pca)
df_scaled_pca.head()

AGE    WEIGHT    HEIGHT      NECK     CHEST   ABDOMEN       HIP  \
0  0.088660  6.280963  0.574790  5.444135  4.204531  5.161290  6.684808   
1 -1.422033 -0.372455  0.301235  0.044490 -0.929933 -1.250360 -0.755929   
2  1.917394 -0.040040 -0.451039  0.291802  0.139747  0.227107 -0.224448   
3  0.963272 -1.062856 -1.203313 -1.150851 -0.145501 -0.572026 -1.371328   
4  0.486211  1.366332 -1.682033  1.322269  2.255336  2.745306  1.803573   

      THIGH      KNEE     ANKLE    BICEPS   FOREARM     WRIST      Prin1  \
0  5.323774  4.366207  3.841274  4.220708  0.166666  3.402526  15.140787   
1 -0.401936 -0.993129  0.826247 -1.085611  0.662531  0.612020  -1.257453   
2 -0.840907 -0.120679 -0.769944 -0.488650 -1.469689  0.612020  -0.727442   
3 -1.222621 -1.491672 -1.065535 -0.190169 -0.676305 -1.427195  -3.210156   
4  0.590521 -0.702312  0.294183  0.804765  0.216252  0.182712   3.246502   

      Prin2     Prin3     Prin4     Prin5    Print6  
0  0.749180  1.730388  2.975628 -1.201404  1.916492  
1 -1.798058 -0.603591 -0.405941  1.333247  0.822237  
2  2.318862 -0.892097  0.682580 -0.503280  0.600209  
3  1.465112  0.457908 -0.575637  0.019772 -0.178803  
4  2.293042  1.828339 -0.023366 -0.406979  1.146568

In [19]:
import numpy as np
df_pca_stat = pd.DataFrame()
df_pca_stat['PrinNo'] = [I for I in range(1,7)]
df_pca_stat['EigenValues'] = pca.explained_variance_
df_pca_stat['EigenValueRation'] = pca.explained_variance_ratio_
df_pca_stat['CumEigenValueRatio'] = np.cumsum(pca.explained_variance_ratio_)
df_pca_stat.round(3)
# 공분산 기준 3개, 상관계수 기준 2개

PrinNo  EigenValues  EigenValueRation  CumEigenValueRatio
0       1        8.072             0.618               0.618
1       2        1.360             0.104               0.723
2       3        1.006             0.077               0.800
3       4        0.670             0.051               0.851
4       5        0.601             0.046               0.897
5       6        0.315             0.024               0.921